### ISSUE TITLE
How could we use Bech32 addresses?

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [vsergeev/ntgbtminer#10]
Hi @vsergeev,

First of all I'd like to thank you for this awesome code. I'm playing a lot with it :)

I'm writing you to ask a question. In this part of the code [here](https://github.com/vsergeev/ntgbtminer/blob/d99f735329ae753fc4f808ea3e327648eb626b66/test_ntgbtminer.py#L251) I've seen that ntgbtminer is using a type [1 bitcoin adress](https://en.bitcoin.it/wiki/Invoice_address).

I'd like to adapt the code in order to use a [Bech32](https://en.bitcoin.it/wiki/Bech32) address type.

It looks like we are transforming the address in [this part](https://github.com/vsergeev/ntgbtminer/blob/d99f735329ae753fc4f808ea3e327648eb626b66/ntgbtminer.py#L119). Do you know what we would need to change in order to use addresses like this one `bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq`?

Thanks in advance ;)

**Comment by vsergeev** [comment]
Sure. You would have to introduce a variant of the [`bitcoinaddress2hash160()`](https://github.com/vsergeev/ntgbtminer/blob/d99f735329ae753fc4f808ea3e327648eb626b66/ntgbtminer.py#L119) function you linked, e.g. `bech32topkh()`, to extract the public key hash from the Bech32 address, and then change the [output script](https://github.com/vsergeev/ntgbtminer/blob/d99f735329ae753fc4f808ea3e327648eb626b66/ntgbtminer.py#L186) from P2PKH to P2WPKH, which is just `OP_0` + the public key hash: `pubkey_script = "00" + bech32topkh(address)`

**Comment by Danilo-Araujo-Silva** [comment]
Thanks a lot @vsergeev for sharing your knowledge :)
Very interesting indeed.

Later I've seen from [here](https://bitcoincore.org/en/doc/0.21.0/rpc/wallet/getnewaddress/) that we can create an address of type legacy, as they call there, and it is the address type 1 that I listed before.

So for now, at least in my case, I'll be proceeding using the type 1 address for my tests.
Either way I think it would be cool if we add support for the other two address types in the future, specially the bech32 one, and maybe support for stratum v1 and v2 as well.

Thank you once again.

If you prefer, I think we can close this issue, or we could keep it open aiming a new feature.

**Comment by vsergeev** [comment]
I'll close for now, but people are always welcome to make a PR with support for new address types.
