### ISSUE TITLE
Incorrect logic in tx_compute_merkle_root

### ISSUE THREAD

**Issue by user46378** [vsergeev/ntgbtminer#7]
I'm not sure, but I think there is an error here:

https://github.com/vsergeev/ntgbtminer/blob/d99f735329ae753fc4f808ea3e327648eb626b66/ntgbtminer.py#L255

**Comment by vsergeev** [comment]
What do you think the error is?

``` python
>>> hashes = ["abc", "def", "123", "456"]
>>> concat = hashes.pop(0) + hashes.pop(0)
>>> concat
'abcdef'
>>> hashes
['123', '456']
>>> 
```
